blog1/accounts/urls.py
from django.urls import path

from .views import signin, signout, signup


app_name = 'accounts'
urlpatterns = [
    path('signup', signup, name='signup'),
    path('signin', signin, name='signin'),
    path('signout', signout, name='signout'),
]

blog1/blog1/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from posts.views import IndexListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexListView.as_view(), name='index'),
    path('accounts/', include('accounts.urls')),
    path('post/', include('posts.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog1/posts/urls.py
from django.urls import path

from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView


app_name = 'posts'
urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create', PostCreateView.as_view(), name='create'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>
<html>

    <head>
    {% include 'head.html' %}
    </head>

    <body>

    {% include 'header.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
    {% include 'scripts.html' %}

    </body>
</html>

templates/footer.html
{% load static %}

<footer class="main-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="logo">
          <h6 class="text-white">Bootstrap Blog</h6>
        </div>
        <div class="contact-details">
          <p>53 Broadway, Broklyn, NY 11249</p>
          <p>Phone: (020) 123 456 789</p>
          <p>Email: <a href="mailto:info@company.com">Info@Company.com</a></p>
          <ul class="social-menu">
            <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="menus d-flex">
          <ul class="list-unstyled">
            <li> <a href="#">My Account</a></li>
            <li> <a href="#">Add Listing</a></li>
            <li> <a href="#">Pricing</a></li>
            <li> <a href="#">Privacy &amp; Policy</a></li>
          </ul>
          <ul class="list-unstyled">
            <li> <a href="#">Our Partners</a></li>
            <li> <a href="#">FAQ</a></li>
            <li> <a href="#">How It Works</a></li>
            <li> <a href="#">Contact</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="latest-posts">
          {% for post in featured_posts %}
          <a href="#">
            <div class="post d-flex align-items-center">
              <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
              <div class="title"><strong>{{ post.title }}</strong><span class="date last-meta">{{ post.timestamp_created|date:"M d, Y" }}</span></div>
            </div>
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="copyrights">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2017. All rights reserved. Your great site.</p>
        </div>
        <div class="col-md-6 text-right">
          <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
            <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/head.html
{% load static %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Bootstrap Blog - B4 Template by Bootstrap Temple</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="all,follow">
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link rel="shortcut icon" href="{% static 'favicon.png' %}">
<!-- Tweaks for older IEs--><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

templates/header.html
<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg">
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center">
        <div class="close-btn"><i class="icon-close"></i></div>
        <div class="row d-flex justify-content-center">
          <div class="col-md-8">
            <form action="#">
              <div class="form-group">
                <input type="search" name="search" id="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search-1"></i></button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <!-- Navbar Brand -->
      <div class="navbar-header d-flex align-items-center justify-content-between">
        {% if request.user.is_authenticated %}
        <span class="navbar-brand">{{ request.user.first_name }} {{ request.user.last_name }}</span>
        {% endif %}
<!--        &lt;!&ndash; Navbar Brand &ndash;&gt;<a href="index.html" class="navbar-brand">Bootstrap Blog</a>-->
        <!-- Toggle Button-->
        <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
      </div>
      <!-- Navbar Menu -->
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="{% url 'index' %}" class="nav-link active ">Home</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'posts:list' %}" class="nav-link ">Posts</a>
          </li>
          <li class="nav-item"><a href="{% url 'posts:create' %}" class="nav-link ">Create</a>
          </li>
          <li class="nav-item"><a href="{% url 'accounts:signout' %}" class="nav-link ">Sign Out</a>
          </li>
          {% else %}
          <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="nav-link ">Sign Up</a>
          </li>
          <li class="nav-item"><a href="{% url 'accounts:signin' %}" class="nav-link ">Sign In</a>
          </li>
          {% endif %}
        </ul>
        <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
      </div>
    </div>
  </nav>
</header>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Hero Section-->
<!--<section style="background: url({% static 'img/hero.jpg' %}); background-size: cover; background-position: center center" class="hero">-->
<!--  <div class="container">-->
<!--    <div class="row">-->
<!--      <div class="col-lg-7">-->
<!--        <h1>Bootstrap 4 Blog - A free template by Bootstrap Temple</h1><a href="#" class="hero-link">Discover More</a>-->
<!--      </div>-->
<!--    </div><a href=".intro" class="continue link-scroll"><i class="fa fa-long-arrow-down"></i> Scroll Down</a>-->
<!--  </div>-->
<!--</section>-->

<!-- Intro Section-->
<section class="intro">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h2 class="h3">Some great intro here</h2>
        <p class="text-big">Place a nice <strong>introduction</strong> here <strong>to catch reader's attention</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi.</p>
      </div>
    </div>
  </div>
</section>

<section class="featured-posts no-padding-top">
  <div class="container">

    <!-- Posts-->
    {% for post in featured_posts %}
    <div class="row d-flex align-items-stretch">
      {% if forloop.counter|divisibleby:2 %}
      <div class="image col-lg-5"><img src="{{ post.thumbnail.url }}" alt="..."></div>
      {% endif %}
      <div class="text col-lg-7">
        <div class="text-inner d-flex align-items-center">
          <div class="content">
            <header class="post-header">
              <div class="category">
                {% for category in post.categories.all %}
                <a href="#">{{ category }}</a>
                {% endfor %}
              </div>
              <a href="{{ post.get_absolute_url }}">
                <h2 class="h4">{{ post.title }}</h2>
              </a>
            </header>
            <p>{{ post.overview }}</p>
            <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                <div class="title"><span>{{ post.author.username }}</span></div></a>
              <div class="date"><i class="icon-clock"></i> {{ post.timestamp_created|timesince }} ago</div>
              <div class="comments"><i class="icon-comment"></i>{{ post.comment_count }}</div>
            </footer>
          </div>
        </div>
      </div>
      {% if not forloop.counter|divisibleby:2 %}
      <div class="image col-lg-5"><img src="{{ post.thumbnail.url }}" alt="..."></div>
      {% endif %}
    </div>
    {% endfor %}

  </div>
</section>

<!-- Divider Section-->
<!--<section style="background: url({% static 'img/divider-bg.jpg' %}); background-size: cover; background-position: center bottom" class="divider">-->
<!--  <div class="container">-->
<!--    <div class="row">-->
<!--      <div class="col-md-7">-->
<!--        <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</h2><a href="#" class="hero-link">View More</a>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</section>-->

<!-- Latest Posts -->
<section class="latest-posts">
  <div class="container">
    <header>
      <h2>Latest from the blog</h2>
      <p class="text-big">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    </header>
    <div class="row">
      {% for post in latest_posts %}
      <div class="post col-md-4">
        <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
        <div class="post-details">
          <div class="post-meta d-flex justify-content-between">
            <div class="date">{{ post.timestamp_created|date:"d M| Y" }}</div>
            <div class="category">
              {% for category in post.categories.all %}
              <a href="#">{{ category }}</a>
              {% endfor %}
            </div>
          </div>
          <a href="{{ post.get_absolute_url }}">
            <h3 class="h4">{{ post.title }}</h3>
          </a>
          <p class="text-muted">{{ post.overview }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<!-- Newsletter Section-->
<section class="newsletter no-padding-top">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Subscribe to Newsletter</h2>
        <p class="text-big">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
      <div class="col-md-8">
        <div class="form-holder">
          <form action="{% url 'index' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              {{ form }}
<!--              <input type="email" name="email" id="email" placeholder="Type your email address">-->
              <button type="submit" class="submit">Subscribe</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Gallery Section-->
<!--<section class="gallery no-padding">-->
<!--  <div class="row">-->
<!--    {% for post in featured_posts %}-->
<!--    <div class="mix col-lg-4 col-md-4 col-sm-6">-->
<!--      <div class="item"><a href="{{ post.thumbnail.url }}" data-fancybox="gallery" class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid">-->
<!--          <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>-->
<!--    </div>-->
<!--    {% endfor %}-->
<!--  </div>-->
<!--</section>-->

{% endblock %}

templates/scripts.html
{% load static %}

<!-- JavaScript files-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
<script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>

templates/sidebar.html
{% load static %}

<aside class="col-lg-4">
  <!-- Widget [Search Bar Widget]-->
  <div class="widget search">
    <header>
      <h3 class="h6">Search the blog</h3>
    </header>
    <form action="{% url 'posts:list' %}" method="get" class="search-form">
      <div class="form-group">
        {% if query %}
        <input type="search" name='q' placeholder="What are you looking for?" value="{{ query }}">
        {% else %}
        <input type="search" name='q' placeholder="What are you looking for?">
        {% endif %}
        <button type="submit" class="submit"><i class="icon-search"></i></button>
      </div>
    </form>
  </div>
  <!-- Widget [Latest Posts Widget]        -->
  <div class="widget latest-posts">
    <header>
      <h3 class="h6">Latest Posts</h3>
    </header>
    <div class="blog-posts">
      {% for post in latest_posts %}
      <a href="{{ post.get_absolute_url }}">
        <div class="item d-flex align-items-center">
          <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
          <div class="title"><strong>{{ post.title }}</strong>
            <div class="d-flex align-items-center">
              <div class="views"><i class="icon-eye"></i> {{ post.view_count }}</div>
              <div class="comments"><i class="icon-comment"></i>{{ post.comment_count }}</div>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
  <!-- Widget [Categories Widget]-->
  <div class="widget categories">
    <header>
      <h3 class="h6">Categories</h3>
    </header>
<!--    {{ category_count }}-->
    {% for category in category_count %}
    <div class="item d-flex justify-content-between"><a href="#">{{ category.categories__category_name }}</a><span>{{ category.dcount }}</span></div>
    {% endfor %}
  </div>
</aside>